# Generated by Django 4.2.2 on 2023-06-17 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, null=True)),
                ('prenom', models.CharField(max_length=100, null=True)),
                ('telephone', models.CharField(max_length=20)),
                ('adresse_mail', models.EmailField(max_length=100, null=True)),
                ('username', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('qr_code', models.ImageField(null=True, upload_to='qr_codes/')),
                ('image', models.ImageField(blank=True, null=True, upload_to='etudiant_images/')),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
