# Generated by Django 4.2.2 on 2023-06-17 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pointme', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='password1',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='password2',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
