# Generated by Django 4.2.2 on 2023-06-18 12:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pointme', '0003_etudiant_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etudiant',
            name='username',
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='adresse_mail',
            field=models.EmailField(max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
