# Generated by Django 4.2.2 on 2023-06-18 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pointme', '0004_remove_etudiant_username_alter_etudiant_adresse_mail_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EtudiantScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_code_data', models.CharField(max_length=200)),
                ('telephone_qr_code', models.CharField(max_length=20)),
                ('date_scan', models.DateField()),
                ('heure_scan', models.TimeField()),
            ],
        ),
    ]
