# Generated by Django 4.2.2 on 2023-06-20 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pointme', '0006_rename_telephone_qr_code_etudiantscan_telephone'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiantscan',
            name='etudiant',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='pointme.etudiant'),
        ),
    ]
