# Generated by Django 4.2.2 on 2023-06-21 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pointme', '0007_etudiantscan_etudiant'),
    ]

    operations = [
    ]
