# Generated by Django 4.2.2 on 2023-06-21 15:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pointme', '0008_auto_20230621_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='date_scan',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='heure_scan',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='qr_code_data',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.DeleteModel(
            name='EtudiantScan',
        ),
    ]
