# Generated by Django 4.2.2 on 2023-06-25 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pointme', '0010_etudiantscan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etudiant',
            name='date_scan',
        ),
        migrations.RemoveField(
            model_name='etudiant',
            name='heure_scan',
        ),
        migrations.AddField(
            model_name='etudiant',
            name='authentifie',
            field=models.BooleanField(default=False),
        ),
    ]
