# Generated by Django 4.2.2 on 2023-06-25 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pointme', '0011_remove_etudiant_date_scan_remove_etudiant_heure_scan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='qr_code_data',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
