# Generated by Django 4.2.2 on 2023-06-28 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pointme', '0014_alter_etudiant_qr_code_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='qr_code_data',
            field=models.JSONField(blank=True, default=dict, unique=True),
        ),
    ]
